// Generated by CoffeeScript 1.4.0
(function() {

  (function($, window, document, undefined_) {
    var Plugin, defaults, pluginName;
    pluginName = 'tacky';
    defaults = {
      itemSelector: 'a',
      parentSelector: null,
      tackedClass: 'tacked',
      activeClass: 'active',
      toggleClass: 'toggle',
      openClass: 'open',
      scrollSpeed: 500,
      scrollEasing: '',
      closeMenuSize: 700,
      markerOffset: .5
    };
    Plugin = function(element, options) {
      var _this = this;
      this.options = $.extend({}, defaults, options);
      this.$nav = $(element);
      this.$toggle_button = this.$nav.find("." + this.options.toggleClass);
      this.init();
      return setTimeout((function() {
        return _this.init();
      }), 500);
    };
    Plugin.prototype = {
      init: function() {
        this.getDOMProperties();
        this.getTargets();
        this.getPositions();
        return this.createEvents();
      },
      getDOMProperties: function() {
        var tackedClass;
        this.document_height = $(document).height();
        this.window_height = $(window).height();
        this.nav_height = this.$nav.outerHeight();
        tackedClass = this.options.tackedClass;
        if (!this.$nav.hasClass(tackedClass)) {
          return this.nav_position = this.$nav.offset().top;
        } else {
          this.$nav.removeClass(tackedClass);
          this.nav_position = this.$nav.offset().top;
          return this.$nav.addClass(tackedClass);
        }
      },
      getTargets: function() {
        this.links = this.$nav.find(this.options.itemSelector);
        return this.targets = this.links.map(function() {
          return $(this).attr('href');
        });
      },
      getPositions: function() {
        var _this = this;
        this.positions = [];
        return this.targets.each(function(i, target) {
          return _this.positions.push($(target).offset().top);
        });
      },
      createEvents: function() {
        var self,
          _this = this;
        $(document).on("scroll.tacky", function() {
          return _this.scroll();
        });
        $(window).on("resize.tacky", function() {
          _this.getDOMProperties();
          _this.closeMenu();
          _this.getPositions();
          return _this.scroll();
        });
        self = this;
        this.links.off('click.tacky').on("click.tacky", function(evt, i) {
          evt.preventDefault();
          return self.scrollTo($(this).attr('href'));
        });
        return this.$toggle_button.off('click.tacky').on('click.tacky', function() {
          return _this.toggleOpen();
        });
      },
      scroll: function() {
        var active_i, i, pos, scroll_marker_position, scroll_nav_position, scroll_percent, scroll_position, scroll_total, _i, _len, _ref;
        scroll_position = $(document).scrollTop();
        scroll_nav_position = $(document).scrollTop() + this.nav_height;
        scroll_marker_position = scroll_position + (this.window_height * this.options.markerOffset);
        if (scroll_position >= this.nav_position) {
          this.toggleNav(true);
          if (scroll_nav_position >= this.positions[0]) {
            scroll_total = this.document_height - this.window_height;
            scroll_percent = scroll_position / scroll_total;
            if (scroll_percent >= .99) {
              scroll_marker_position += this.window_height;
            }
            active_i = null;
            _ref = this.positions;
            for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
              pos = _ref[i];
              if (scroll_marker_position >= pos) {
                active_i = i;
              }
            }
            return this.setActiveMenuItem(active_i);
          } else {
            return this.clearActiveMenuItem();
          }
        } else {
          return this.toggleNav(false);
        }
      },
      toggleOpen: function() {
        var openClass, speed, tackedClass,
          _this = this;
        openClass = this.options.openClass;
        tackedClass = this.options.tackedClass;
        if (this.$nav.hasClass(openClass)) {
          return this.$nav.removeClass(openClass);
        } else {
          if (this.$nav.hasClass(tackedClass)) {
            return this.$nav.addClass(openClass);
          } else {
            speed = this.options.scrollSpeed / 2;
            $("html, body").stop().animate({
              scrollTop: this.nav_position + 1
            }, speed, this.options.scroll_easing);
            return setTimeout((function() {
              return _this.$nav.addClass(openClass);
            }), speed);
          }
        }
      },
      scrollTo: function(target_id) {
        var position, position_index;
        position_index = $.inArray(target_id, this.targets);
        position = this.positions[position_index] - this.nav_height;
        if (this.$nav.hasClass(this.options.openClass)) {
          $("html, body").stop().animate({
            scrollTop: position
          }, 0);
          return this.toggleOpen();
        } else {
          return $("html, body").stop().animate({
            scrollTop: position
          }, this.options.scrollSpeed, this.options.scroll_easing);
        }
      },
      toggleNav: function(stick) {
        if (stick) {
          return this.$nav.addClass(this.options.tackedClass);
        } else {
          this.$nav.removeClass(this.options.tackedClass);
          return this.clearActiveMenuItem();
        }
      },
      setActiveMenuItem: function(i) {
        var $active_item, active_class;
        this.clearActiveMenuItem();
        if (i >= 0) {
          active_class = this.options.activeClass;
          $active_item = this.links.eq(i);
          return $active_item.parent().addClass(active_class);
        }
      },
      clearActiveMenuItem: function() {
        var active_class;
        active_class = this.options.activeClass;
        return this.$nav.find('.' + active_class).removeClass(active_class);
      },
      closeMenu: function() {
        var closeMenuSize, document_width;
        closeMenuSize = this.options.closeMenuSize;
        if (closeMenuSize >= 0) {
          document_width = $(document).width();
          if (document_width >= closeMenuSize) {
            return this.$nav.removeClass(this.options.openClass);
          }
        }
      }
    };
    return $.fn[pluginName] = function(options) {
      var args, returns, scoped_name;
      args = arguments;
      scoped_name = "plugin_" + pluginName;
      if (options === undefined || typeof options === "object") {
        return this.each(function() {
          if (!$.data(this, scoped_name)) {
            return $.data(this, scoped_name, new Plugin(this, options));
          }
        });
      } else if (typeof options === "string" && options[0] !== "_" && options !== "init") {
        returns = void 0;
        this.each(function() {
          var instance;
          instance = $.data(this, scoped_name);
          if (instance instanceof Plugin && typeof instance[options] === "function") {
            returns = instance[options].apply(instance, Array.prototype.slice.call(args, 1));
          }
          if (options === "destroy") {
            return $.data(this, scoped_name, null);
          }
        });
        if (returns !== undefined) {
          return returns;
        } else {
          return this;
        }
      }
    };
  })(jQuery, window, document);

}).call(this);
